### ISSUE TITLE
Fragmentation in a single file

### ISSUE THREAD

**Issue by constraintAutomaton** [SolidBench/rdf-dataset-fragmenter.js#28]
For some experiments for example comparing an LTQP method with a single endpoints method or to more easily know the expected results of a query, it is interesting to have a benchmark in one file. So I am wondering if a strategy to output everything in one file would be useful or if there are easier (while still following the Solidbench pipeline) ways to do that.

**Comment by rubensworks** [comment]
Should be possible by creating a new constant-based fragmentation strategy.
